Add checkbox to push artifacts for failed build
UrbanCode/jenkins-pipeline-ucd-plugin pull request #22
Opened 2021-02-26 03:22 UTC by AjeetGupta

2021-04-15 07:00 UTC, deepaannjohn requested changes

2021-04-15 07:00 UTC, deepaannjohn commented on src/main/java/com/urbancode/jenkins/plugins/ucdeploy/UCDeployPublisher.java
> +                listener.getLogger().println("Continue to push even build is failed");
Pushing
```suggestion
                listener.getLogger().println("Pushing Failed Build");   
```

2021-04-15 07:00 UTC, deepaannjohn commented on src/main/java/com/urbancode/jenkins/plugins/ucdeploy/UCDeployPublisher.java
> +            if(pushFailedBuild != true){
```suggestion
            if(pushFailedBuild != true || build.getResult() == Result.ABORTED){
```

2021-04-15 07:00 UTC, deepaannjohn commented on src/main/resources/com/urbancode/jenkins/plugins/ucdeploy/UCDeployPublisher/config.jelly
> +            <f:entry field="pushFailedBuild" title="Push Failed build" help="${helpURL}/create/delivery/push/pushFailedBuild.html">
```suggestion
            <f:entry field="pushFailedBuild" title="Push Failed Build" help="${helpURL}/create/delivery/push/pushFailedBuild.html">
```

2021-04-15 07:46 UTC, AjeetGupta commented
[Don't merge this code]

2021-06-30 11:06 UTC, deepaannjohn approved these changes

2021-06-30 11:06 UTC, merged